services:
  - type: web
    name: personal-finance-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000

  - type: web
    name: personal-finance-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
